---
title: "natural deduction: conjunction"
subtitle: "PHIL 220. Introduction to Logic"
author: "Gabriel Uzquiano"
format:
  revealjs:
    theme: [default, custom.scss]
    output-file: natural-deduction-conjunction-slides.html
    slide-number: c/t
    chalkboard: true          # press B for a blank board, C to draw on a slide
    preview-links: auto       # links open in an overlay, without leaving the deck
    history: false
    transition: none          # no swooping; the content should not move
    center: false
    width: 1100
    height: 750
    margin: 0.06
    hash-type: title
    menu:
      side: left
---

# natural deduction: conjunction {.divider}

Truth tables provide a decision method for propositional validity. They enable us to decide in a finite number of steps whether a given argument in propositional logic is valid:

:::{.incremental}
- If the argument is valid, there is no row of the truth table on which the premises come out true and the conclusion false.

- If the argument is invalid, there is at least one row in which the premises come out true and the conclusion is false. 
  
    There is a counterexample to the validity of the argument.
:::

## the limits of truth tables 


Unfortunately, truth tables are not helpful when it comes to more complex formal languages for which we will have resort to a different strategy.

. . .

The other strategy for propositional validity involves proofs:

. . .

If an argument is valid, then there is **a proof** of the conclusion from the premises, which consists of **a chain of simple inferences** governed by sanctioned **rules of inference associated with each connective.**


## the plan {.smaller}

::: {.columns}

::: {.column width="58%"}
::: {.argument}
1. Interest rates are high.
2. If interest rates are high and economic growth is slow, then inflation
   will come down.
3. Economic growth is slow.

::: {.conclusion}
4. Inflation will come down.
:::
:::

:::

::: {.column width="42%"}
We break down the argument into two simple steps:

::: {.incremental}
- from 1 and 3: 
  
    *interest rates are high and economic growth is slow.*
    
- from 2 and the above: 
  
    *inflation will come down.*
:::

:::
:::

::: {.incremental}
- One step proceeds from premises 1 and 3 and is sanctioned by the semantic behavior of **and**: 


    given $\varphi$ and $\psi$, we may infer the conjunction $\varphi$ **and** $\psi$.
    
- The other step proceeds from premise 2 and the outcome of the prior step and is sanctioned by the behavior of **if** ... **then**: given a conditional 

    **if** $\varphi$, **then** $\psi$

    and 

    $\varphi$, 

    we are free to conclude $\psi$.
:::


## translation into propositional logic {.smaller}

::: {.columns}
::: {.column width="58%"}
::: {.argument}
$p$: Interest rates are high.

$q$: Economic growth is slow.

$r$: Inflation will come down.
:::

::: {.argument}
1. $p$
2. $(p \wedge q) \to r$
3. $q$

::: {.conclusion}
4. $r$
:::
:::

:::

::: {.column width="42%"}
::: {style="height: 60px;"}
:::

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p, (p /\ q) -> r, q :|-: r
|p :assumption
|(p /\ q) -> r :assumption
|q :assumption
|p/\q :I/\ 1,3
|r :E-> 2, 4
```
:::
:::

::: {.incremental}
- Lines 1, 2, and 3 are premises
- Line 4 is obtained from lines 1 and 3 by $I\wedge$: 

    from $\varphi$ and $\psi$, infer $\varphi \wedge \psi$
    
- Line 5 is obtained from lines 2 and 4 by the rule of inference $E\to$: 
  
    from if $\varphi$, then $\psi$ and $\varphi$ infer $\psi$
    
- Line 5 completes the proof because the formula is exactly the **conclusion** we are after.
:::



## what is a proof?

::: {.definition}
A **proof** in propositional logic is a finite sequence of formulas each of which is either 

  - an *assumption*, or 
  
  - the *outcome of an application* of a sanctioned *rule of inference* to prior formulas. 
  
The last formula is the *conclusion*.
:::

. . . 

::: {style="height: 30px;"}
:::


If an argument of propositional logic is valid, then *there is a proof of its conclusion from its premises*.

## a catalogue of rules of inference

Each connective comes with at least two rules of inference:

::: {.incremental}
- an **introduction** rule: 
  
    when you may *write* a formula with that connective as main connective
    
- an **elimination** rule: 

    when you may *exploit* one that is already available from a prior line
:::

. . .

Before we look at them, there is one structural rule to our disposal.

# repetition {.divider}

There is just one structural rule.



## repetition

::: {.argument}
You may repeat a formula $\varphi$ on a line if it is available on a prior
line of the derivation.
:::

. . .

::: {style="height: 60px;"}
:::

The simplest proof you will ever write:



::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p$

::: {.conclusion}
2. $p$
:::
:::

:::

::: {.column width="42%"}


```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p :|-: p
|p :assumption
|p :rep 1
```
$$
p \vdash p
$$

:::

:::




# conjunction {.divider}

Two rules:

::: {.incremental}
- one **introduction rule** explains when you may write a conjunction $\varphi \wedge \psi$ on the basis of prior lines.

- one **elimination rule** explains how to exploit a conjunction $\varphi \wedge \psi$ from a prior line.
:::

## introduction rule: $I\wedge$


::: {.argument}
1. $\varphi$
2. $\psi$

::: {.conclusion}
3. $\varphi \wedge \psi$
:::
:::

You may write $\varphi \wedge \psi$ if $\varphi$ and $\psi$ are both available
at prior lines.


## how to apply $I \wedge$ 

::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p$
2. $q$

::: {.conclusion}
3. $p \wedge q$
:::
:::

:::

::: {.column width="42%"}



```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p, q :|-: p /\ q
|p :assumption
|q :assumption
|p/\q :I/\ 1,2
```

$$
p, q \vdash p \wedge q
$$
:::

:::


## one more example 

::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p$
2. $q$
3. $r$

::: {.conclusion}
4. $(p \wedge r) \wedge q$
:::
:::

:::

::: {.column width="42%"}

::: {style="height: 10px;"}
:::

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p, q, r :|-: (p /\ r) /\ q
|p :assumption
|q :assumption
|r :assumption
|p/\r :I/\ 1,3
|(p/\r)/\q :I/\ 2,4
```

$$
p, q, r \vdash (p \wedge r) \wedge q
$$
:::

:::


## elimination rule: $E\wedge$

::: {.columns}
::: {.column width="48%"}
::: {.argument}
1. $\varphi \wedge \psi$

::: {.conclusion}
2. $\varphi$
:::
:::
:::
::: {.column width="48%"}
::: {.argument}
1. $\varphi \wedge \psi$

::: {.conclusion}
2. $\psi$
:::
:::
:::
:::

You may write either conjunct of a conjunction available at a prior
line.


## how to apply $E \wedge$ 

::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p$
2. $q \wedge r$

::: {.conclusion}
3. $p \wedge r$
:::
:::

:::

::: {.column width="42%"}



```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p, (q /\ r) :|-: p /\ r
|p :assumption
|q/\r :assumption
|r :E/\ 2
|p/\r :I/\ 1,3
```

$$
p, q \wedge r \vdash p \wedge r
$$

:::

:::


## both rules in action 

::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $(p \wedge q) \wedge (r \wedge t)$

::: {.conclusion}
2. $(p \wedge r) \wedge (q \wedge t)$
:::
:::

:::

::: {.column width="42%"}

::: {style="height: 10px;"}
:::

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. (p /\ q) /\ (r /\ t) :|-: (p /\ r) /\ (q /\ t)
|(p/\q)/\(r/\t) :assumption
|p/\q :E/\ 1
|r/\t :E/\ 1
|p :E/\ 2
|r :E/\ 3
|q :E/\ 2
|t :E/\ 3
|p/\r :I/\ 4, 5
|q/\t :I/\ 6, 7
|(p/\r)/\(q/\t) :I/\ 8, 9
```

$$
(p\wedge q) \wedge (r \wedge t) \vdash (p \wedge r) \wedge (q \wedge t)
$$
:::

:::


# practice {.divider} 

Three derivations, given only their assumptions.

## exercise 1 {.smaller}

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none"}
1. p, q, r :|-: (p /\ q) /\ (q /\ r)
|p :assumption
|q :assumption
|r :assumption
```



## exercise 2 {.smaller}

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none"}
1. p /\ q, r /\ s :|-: (p /\ r) /\ (q /\ s)
|p/\q :assumption
|r/\s :assumption
```


## exercise 3 {.smaller}

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none"}
1. p /\ (q /\ r), (p /\ t) /\ s :|-: r /\ t
|p/\(q/\r) :assumption
|(p/\t)/\s :assumption
```





## next time

We will now provide introduction and elimination rules for the conditional and disjunction.


