---
title: "natural deduction: conditional and disjunction"
subtitle: "PHIL 220. Introduction to Logic"
author: "Gabriel Uzquiano"
format:
  revealjs:
    theme: [default, custom.scss]
    output-file: natural-deduction-conditional-disjunction-slides.html
    slide-number: c/t
    chalkboard: true          # press B for a blank board, C to draw on a slide
    preview-links: auto       # links open in an overlay, without leaving the deck
    history: false
    transition: none          # no swooping; the content should not move
    center: false
    width: 1100
    height: 750
    margin: 0.06
    hash-type: title
    menu:
      side: left
---

# natural deduction: conditional and disjunction {.divider}

We have introduction and elimination rules for conjunction. We now look at two more connectives: conditional and disjunction.



## where we left off

::: {.incremental}
- $R$:  repetition $\checkmark$
- I$\wedge$: conjunction introduction $\checkmark$
- E$\wedge$: conjunction elimination $\checkmark$
- E$\to$: conditional elimination (*modus ponens*) *to do*
- I$\to$: conditional introduction (*conditional proof*) *to do*
- I$\vee$: disjunction introduction *to do*
- E$\vee$: disjunction elimination (*proof by cases*) *to do*
:::

# the conditional {.divider}

Two rules: 

- one **elimination rule** explains how to exploit a conditional $\varphi \to \psi$ from a prior line. 

- one **introduction rule** explains when you may write a conditional $\varphi \to \psi$ on the basis of prior lines.

## elimination rule: E$\to$

::: {.argument}
1. $\varphi \to \psi$
2. $\varphi$

::: {.conclusion}
3. $\psi$
:::
:::

You may write $\psi$ if $\varphi \to \psi$ and $\varphi$ are both available at prior lines. This is what we have called *modus ponens* in the past.

## how to apply E$\to$ 

::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $(p \wedge q) \to t$
2. $p$
3. $q$

::: {.conclusion}
4. $t$
:::
:::

:::

::: {.column width="42%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. (p /\ q) -> t, p, q :|-: t
|(p /\ q) -> t :assumption
|p :assumption
|q :assumption
|p/\q :I/\ 2,3
|t :E-> 1,4
```

$$
(p \wedge q) \to t, p, q \vdash t
$$
:::
:::


## one more example 

::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p \to (q \to r)$
2. $p \wedge q$

::: {.conclusion}
3. $r$
:::
:::

:::

::: {.column width="42%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p -> (q -> r), p /\ q :|-: r
|p -> (q -> r) :assumption
|p/\q :assumption
|p :E/\ 2
|q -> r :E-> 1,3
|q :E/\ 2
|r :E-> 4,5
```

$$
p \to (q \to r), p \wedge q \vdash r
$$

:::
:::




## practice {.smaller}

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none"}
1. p, (p /\ q) -> r, p -> q :|-: r
|p :assumption
|(p /\ q) -> r :assumption
|p -> q :assumption
```




## introduction rule: I$\to$ {.smaller}

You may write $\varphi \to \psi$ if you can prove $\psi$ from the **assumption** that $\varphi$. 

Once you complete the subproof, bracket the lines of that subproof and never appeal to them again.


## how to apply I$\to$ {.smaller}


::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p \to (q \wedge r)$

::: {.conclusion}
2. $p \to r$
:::
:::

:::

::: {.column width="42%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p -> (q /\ r) :|-: p -> r
|p -> (q /\ r) :assumption
| p :assumption
| q/\r :E-> 1,2
| r :E/\ 3
|p -> r :I-> 2-4
```

$$
p \to (q \wedge r) \vdash p \to r
$$
:::

::: {.incremental}
- line 2 opens the subproof
- line 5 closes it and discharges the assumption.
:::
:::



## another application {.smaller}


::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p \to r$
2. $q \to t$

::: {.conclusion}
3. $(p \wedge q) \to (r \wedge t)$
:::
:::

:::

::: {.column width="42%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p -> r, q -> t :|-: (p /\ q) -> (r /\ t)
|p -> r :assumption
|q -> t :assumption
| p/\q :assumption
| p :E/\ 3
| r :E-> 1,4
| q :E/\ 3
| t :E-> 2,6
| r/\t :I/\ 5,7
|(p /\ q) -> (r /\ t) :I-> 3-8
```

$$
p \to r, q \to t \vdash (p \wedge q) \to (r \wedge t)
$$

:::


:::




## practice

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none"}
1. p -> (q -> r) :|-: q -> (p -> r)
|p -> (q -> r) :assumption
```






# disjunction {.divider}

Two rules:

- one **introduction rule** to explain when to write a disjunction $\varphi \vee \psi$ on the basis of prior lines.

- one **elimination rule** to explain how to exploit a disjunction $\varphi \vee \psi$ from a prior line

## introduction rule: I$\vee$

::: {.argument}
1. $\varphi$

::: {.conclusion}
2. $\varphi \vee \psi$
:::
:::

You may write $\varphi \vee \psi$ once either disjunct is available at a
prior line.



## how to apply I$\vee$ 


::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p$
2. $q$

::: {.conclusion}
2. $(p \vee r) \vee (r \vee q)$
:::
:::

:::

::: {.column width="42%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p, q :|-: (p \/ r) /\ (r \/ q)
|p :assumption
|q :assumption
|p\/r :I\/ 1
|r\/q :I\/ 2
|(p\/r)/\(r\/q) :I/\ 3,4
```

$$
p, q \vdash (p \vee r) \vee (r \vee q)
$$
:::

:::


## another application

::: {.columns}
::: {.column width="58%"}
::: {.argument}
1. $p$
2. $(p \vee q) \to r$

::: {.conclusion}
2. $r$
:::
:::

:::

::: {.column width="42%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. p, (p \/ q) -> r :|-: r
|p :assumption
|(p \/ q) -> r :assumption
|p\/q :I\/ 1
|r :E-> 2,3
```

$$
p, (p \vee q) \to r \vdash r
$$
:::


:::





## practice {.smaller}

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none"}
1. p /\ q :|-: (p \/ r) /\ (q \/ t)
|p/\q :assumption
```



## elimination rule: E$\vee$ {.smaller}

::: {.argument}
1. $\varphi \vee \psi$
2. $\varphi \to \chi$
3. $\psi \to \chi$

::: {.conclusion}
4. $\chi$
:::
:::

You may write $\chi$ on the basis of $\varphi \vee \psi$ in the presence of two conditionals:

- $\varphi \to \chi$

- $\psi \to \chi$

You will often have to establish the conditionals by indepedendent applications of I$\to$



## how to apply E$\vee$ {.smaller}

::: {.columns}
::: {.column width="58%"}

::: {.argument}
1. $p \to r$
2. $q \to r$
3. $r \to t$
4. $p \vee q$

::: {.conclusion}
4. $t$
:::
:::

:::

::: {.column width="42%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify" height="590px"}
1. p -> r, q -> r, r -> t, p \/ q :|-: t
|p -> r :assumption
|q -> r :assumption
|r -> t :assumption
|p\/q :assumption
| p :assumption
| r :E-> 1, 5
| t :E-> 3, 6
|p -> t :I-> 5-7
| q :assumption
| r :E-> 2, 9
| t :E-> 3, 10
|q -> t :I-> 9-11
|t :E\/ 4, 8, 12
```



:::

:::


## two more applications {.smaller}

::: {.columns}
::: {.column width="48%"}
$$
(p \wedge q) \vee (r \wedge p) \vdash p
$$

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. (p /\ q) \/ (r /\ p) :|-: p
|(p /\ q) \/ (r /\ p) :assumption
| p/\q :assumption
| p :E/\ 2
|(p/\q) -> p :I-> 2-3
| r/\p :assumption
| p :E/\ 5
|(r/\p) -> p :I-> 5-6
|p :E\/ 1, 4, 7
```
:::
::: {.column width="48%"}
$$
(p \wedge q) \vee (r \wedge p) \vdash q \vee r
$$

```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify"}
1. (p /\ q) \/ (p /\ r) :|-: q \/ r
|(p /\ q) \/ (p /\ r) :assumption
| p/\q :assumption
| q :E/\ 2
| q\/r :I\/ 3
|(p/\q) -> (q\/r) :I-> 2-4
| p/\r :assumption
| r :E/\ 6
| q\/r :I\/ 7
|(p/\r) -> (q\/r) :I-> 6-8
|q\/r :E\/ 1, 5, 9
```
:::
:::

# worked example {.divider}

All four rules, on an argument from natural language.


## a natural language argument {.smaller}

> The British are coming by land or they are coming by sea. Paul Revere will
> light one lamp if the British are coming by land. However, Paul Revere will
> light two lamps if they are coming by sea. So, Paul Revere will light one
> lamp or he will light two lamps.


**in premise-conclusion form**

::: {.argument}
1. The British are coming by land or they are coming by sea.
2. If the British are coming by land, then Paul Revere will light one lamp.
3. If the British are coming by sea, then Paul Revere will light two lamps.

::: {.conclusion}
4. Paul Revere will light one lamp or he will light two lamps.
:::
:::

## translation {.smaller}

::: {.columns}
::: {.column width="48%"}
::: {style="font-size: 0.72em;"}
::: {.argument}
$p$: The British are coming by land.

$q$: The British are coming by sea.

$r$: Paul Revere will light one lamp.

$s$: Paul Revere will light two lamps.
:::
:::

::: {.argument}
1. $p \vee q$
2. $p \to r$
3. $q \to s$

::: {.conclusion}
4. $r \vee s$
:::
:::

:::

::: {.column width="52%"}
```{.ProofChecker .GamutPND options="indent resize fonts popout render tabindent" submission="none" card="verify" height="560px"}
1. p \/ q, p -> r, q -> s :|-: r \/ s
|p\/q :assumption
|p -> r :assumption
|q -> s :assumption
| p :assumption
| r :E-> 2,4
| r\/s :I\/ 5
|p -> (r\/s) :I-> 4-6
| q :assumption
| s :E-> 3,8
| r\/s :I\/ 9
|q -> (r\/s) :I-> 8-10
|r\/s :E\/ 1, 7, 11
```
:::
The argument is **valid** because there is a proof of the conclusion from its premises.
:::



## four rules, one system

::: {.incremental}
- E$\to$: from $\varphi \to \psi$ and $\varphi$, infer $\psi$
- I$\to$: derive $\psi$ from assumed $\varphi$, discharge to get $\varphi \to \psi$
- I$\vee$: from $\varphi$ (or $\psi$), infer $\varphi \vee \psi$
- E$\vee$: from $\varphi \vee \psi$, $\varphi \to \chi$, $\psi \to \chi$, infer $\chi$
:::


