---
title: "validity"
subtitle: "PHIL 220. Introduction to Logic"
author: "Gabriel Uzquiano"

filters:
  - carnap-widgets.lua
  - checker-widget.lua
  - truth-table-widgets.lua

format:
  revealjs:
    theme: [default, custom.scss]
    output-file: validity-slides.html
    slide-number: c/t
    chalkboard: true          # press B for a blank board, C to draw on a slide
    preview-links: auto       # links open in an overlay, without leaving the deck
    history: false
    transition: none          # no swooping; the content should not move
    center: false
    width: 1100
    height: 750
    margin: 0.06
    hash-type: title
    menu:
      side: left
---

# validity {.divider}

We aim for a framework within which to assess the validity of argument forms exemplified by natural language arguments.

## from English to propositional logic {.smaller}

We will extract a propositional form from each natural language argument:

::::::::: columns
::::: {.column style="width:60%;"}
**argument**

:::: argument
1.  If mica is a metal, then it conducts electricity.
2.  Mica does not conduct electricity.

::: conclusion
2.  Mica is not a metal.
:::
::::
:::::

::::: {.column style="width:40%;"}
**argument form**

:::: argument
1.  $p \to q$
2.  $\neg q$

::: conclusion
2.  $\neg p$
:::
::::
:::::

**key**

$p$ : Mica is a metal

$q$ : Mica conducts electricity
:::::::::

:::: fragment
::: {style="margin-top: 4em;"}
:::

Is this a *valid* argument form?
::::

## validity {.smaller}

::: definition
An argument of propositional logic is **valid** iff there is **no assignment** of truth values to its propositional variables on which **the premises are true** and **the conclusion is false**.
:::

```{.TruthTable mode="validity" height="490px"}
(p -> q)
~q
~p
```

## from English to propositional logic {.smaller}

:::::::::: columns
::::: {.column style="width:60%;"}
**argument**

:::: argument
1.  If the government levies another tax on companies, then employment will fall.
2.  The government will not levy another tax.

::: conclusion
2.  Employment will not fall.
:::
::::
:::::

:::::: {.column style="width:40%;"}
::: {style="margin-top: 1em;"}
:::

**argument form**

:::: argument
1.  $p \to q$
2.  $\neg p$

::: conclusion
2.  $\neg q$
:::
::::
::::::

**key**

$p$ : The government levies another tax on companies.

$q$ : Employment falls.
::::::::::

:::: fragment
::: {style="margin-top: 4em;"}
:::

Is this a *valid* argument form?
::::

## validity {.smaller}

```{.TruthTable mode="validity" height="460px"}
(p -> q)
~p
~q
```

## counterexamples to validity {.smaller}

::: definition
Given an **invalid** argument, a **counterexample** to validity is **an assignment** of truth values to propositional variables **on which the premises come out true** and **the conclusion comes out false**.
:::

:::::::::::::::::: {columns}
::::::::: {.column style="width:50%;"}
::::: fragment
**invalid argument form**

:::: argument
1.  $p \to q$
2.  $\neg p$

::: conclusion
2.  $\neg q$
:::
::::
:::::

::::: fragment
**invalid argument form**

:::: argument
1.  $p \vee q$
2.  $p \to \neg r$

::: conclusion
2.  $\neg r \vee p$
:::
::::
:::::
:::::::::

:::::::::: {.column style="width:50%;"}
::::: fragment
:::: {style="margin-left: 4em;"}
**counterexample**

::: {style="margin-top: 2em;"}
:::

$p$ : $F$

$q$ : $T$
::::
:::::

::: {style="margin-top: 4em;"}
:::

::::: fragment
:::: {style="margin-left: 4em;"}
**counterexample**

::: {style="margin-top: 2em;"}
:::

$p$ : $F$

$q$ : $T$

$r$ : $T$
::::
:::::
::::::::::
::::::::::::::::::

# how to search for a counterexample {.smaller}

One way to check the validity of an argument is to scan a **full** truth table, row by row, in search of a counterexample, but another is to use a **partial** truth table **to search for a counterexample.**

This method is particularly helpful for complex arguments that involve more than two propositional variables. We would rather not scan 16 or 32 rows of a full truth table for an argument in which 4 or 5 propositional variables are involved.

## the search for a counterexample method {.smaller}

Consider the argument form:

:::: argument
1.  $p \to (q \to r)$
2.  $\neg r \to p$

::: conclusion
3.  $\neg r \to q$
:::
::::

To search for a counterexample, follow the steps below:

::: {.incremental}
1.  Focus on assignments that **make the conclusion false**<br>For $\neg r \to q$ to be false, $\neg r$ must be true and $q$ must be false. Therefore, we look at assignments on which both $r$ is false and $q$ is false.

2.  Ask **which of the assignments that remain make the premises true**.<br>There are just two options for $r$ is false and $q$ is false, namely, assignments on which $p$ is true and assignments on which $p$ is false. If $p$ is true and $r$ and $q$ are false, then premise 1 will be *true* because $q \to r$ comes out true and premise 2 will be true because $\neg r \to p$ has a true consequent.

3.  If you **find a counterexample**, then **the argument is invalid**.<br>Make $p : T$, $q : F$, $r : F$.
:::

## example 1 {.smaller}

::::::::: columns
:::::: {.column style="width:45%;"}
::::: fragment
:::: argument
1.  $p \to ((q \wedge \neg r) \vee (r \wedge q))$
2.  $p \wedge q$
3.  $r \vee \neg p$

::: conclusion
2.  $q \to \neg r$
:::
::::

There are \\(2\^3 = 8\\) assignments.

A full truth table would require 8 rows.

We now employ the **search for counterexample method**:
:::::
::::::

:::: {.column style="width:55%;"}
::: fragment
1.  Find assignments that **make the conclusion false**

To make

$$
q \to \neg r
$$

**false**, we must have:

$$
q : T \qquad r : T
$$

So, we need consider only **2** rows out the 8:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r &  q \to \neg r  \ \\
\hline
T & T & T & \color{red}{F}  \\
F & T & T &  \color{red}{F} \\
\hline
\end{array}
$$
:::
::::
:::::::::

## filter the candidate rows {.smaller}

2.  Ask **which of the assignments that remain make the premises true**.

To make the second premise true, we focus on the first row:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r & p \to ((q \wedge \neg r) \vee (r \wedge q)) & p \wedge q & r \vee \neg p & q \to \neg r \\
\hline
T & T & T & &\color{red}{T} & &  \color{red}{F}  \\
F & T & T & & F & &  \color{red}{F} \\
\hline
\end{array}
$$

::: fragment
Check the other two premises now:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r & p \to ((q \wedge \neg r) \vee (r \wedge q)) & p \wedge q & r \vee \neg p & q \to \neg r \\
\hline
T & T & T & \color{red}{T} &\color{red}{T} & \color{red}{T} &  \color{red}{F}  \\
F & T & T & & F & &  \color{red}{F} \\
\hline
\end{array}
$$

We conclude that \\(T T T\\) is a counterexample.

**The argument is invalid**.
:::

## truth table {.smaller}

Consider the assignment \\(p : T,\\ q : T,\\ r : T\\).

```{.TruthTable mode="validity" height="460px"}
p->((q/\~r)\/(r/\q))
p/\q
r\/~p
q->~r
```

## example 2 {.smaller}

::::::::: columns
:::::: {.column style="width:45%;"}
::::: fragment
:::: argument
1.  $p \vee q$
2.  $\neg r \to q$

::: conclusion
3.  $p \to r$
:::
::::

There are \\(2\^3 = 8\\) assignments.

A full truth table would require 8 rows.

We now employ the **search for counterexample method**:
:::::
::::::

:::: {.column style="width:55%;"}
::: fragment
1.  Find assignments that **make the conclusion false**

To make

$$
p \to  r
$$

**false**, we must have:

$$
p : T \qquad r : F
$$

So, we need consider only **2** rows out the 8:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r &  p \to r  \ \\
\hline
T & T & F & \color{red}{F}  \\
T & F & F &  \color{red}{F} \\
\hline
\end{array}
$$
:::
::::
:::::::::

## filter the candidate rows {.smaller}

2.  Ask **which of the assignments that remain make the premises true**.

Both rows verify the first premise:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r & p \vee q & \neg r \to q & p \to  r \\
\hline
T & T & F & \color{red}{T} &  &   \color{red}{F}  \\
T & F & F & \color{red}{T} &  &   \color{red}{F} \\
\hline
\end{array}
$$

::: fragment
Check the other premise now:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r & p \vee q & \neg r \to q & p \to  r \\
\hline
T & T & F & \color{red}{T} & \color{red}{T} &   \color{red}{F}  \\
T & F & F & \color{red}{T} & F &   \color{red}{F} \\
\hline
\end{array}
$$

We conclude that \\(T T F\\) is a counterexample.

**The argument is invalid**.
:::

## truth table {.smaller}

Consider the assignment \\(p : T,\\ q : T,\\ r : F\\).

```{.TruthTable mode="validity" height="460px"}
p \/q
~r -> q
p->r
```

## from English to propositional logic {.smaller}

:::::::::: columns
::::: {.column style="width:50%;"}
**argument**

:::: argument
1.  If the government levies another tax on companies, then employment will fall or inflation will rise.
2.  If inflation rises, then if the government levies another tax, then employment will fall.

::: conclusion
3.  Employment will fall or inflation will rise.
:::
::::
:::::

:::::: {.column style="width:50%;"}
::: {style="margin-top: 1em;"}
:::

**argument form**

:::: argument
1.  $p \to (q \vee r)$
2.  $r \to (p \to q)$

::: conclusion
3.  $q \vee r$
:::
::::
::::::
::::::::::

**key**

$p$ : The government levies another tax on companies.

$q$ : Employment falls.

$r$ : Inflation rises.

## in search of a counterexample {.smaller}

1.  Find assignments that **make the conclusion false**

To make

$$
q \vee  r
$$

**false**, we must have:

$$
q : F \qquad r : F
$$

So, we need consider only **2** rows out the 8:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r &  q \vee r  \ \\
\hline
T & F & F & \color{red}{F}  \\
F & F & F &  \color{red}{F} \\
\hline
\end{array}
$$

## filter the assignments {.smaller}

2.  Ask **which of the assignments that remain make the premises true**.

Only the second row verifies the first premise:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r &  p \to (q \vee r) & r \to (p \to q) & q \vee r  \ \\
\hline
T & F & F & F& &  \color{red}{F}  \\
F & F & F & \color{red}{T} & & \color{red}{F} \\
\hline
\end{array}
$$

::: fragment
Check the other premise now:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r &  p \to (q \vee r) & r \to (p \to q) & q \vee r  \ \\
\hline
T & F & F & F& &  \color{red}{F}  \\
F & F & F & \color{red}{T} & \color{red}{T} & \color{red}{F} \\
\hline
\end{array}
$$

We conclude that \\(F F F\\) is a counterexample to validity. **The argument is invalid.**
:::

## from English to propositional logic {.smaller}

:::::::::: columns
::::: {.column style="width:50%;"}
**argument**

:::: argument
1.  If the coin lands heads, it will not land tails, and if it lands tails, it will not land heads.
2.  It is not the case that I tossed the coin and it landed heads.
3.  It is not the case that if I tossed the coin, then it landed tails.

::: conclusion
3.  I did not toss the coin.
:::
::::
:::::

:::::: {.column style="width:50%;"}
::: {style="margin-top: 1em;"}
:::

**argument form**

:::: argument
1.  $(p \to \neg q) \wedge (q \to \neg r)$
2.  $\neg (r \wedge p)$
3.  $\neg (r \to q)$

::: conclusion
3.  $\neg r$
:::
::::
::::::
::::::::::

**key**

$p$ : The coin landed heads.

$q$ : The coin landed tails.

$r$ : I tossed the coin.

## in search of a counterexample {.smaller}

1.  Find assignments that **make the conclusion false**

To make

$$
\neg  r
$$

**false**, we must have:

$$
r : T
$$

So, we need consider only **4** rows out the 8:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r &  \neg r  \ \\
\hline
T & T & T &  \color{red}{F} \\
F & T & T &  \color{red}{F} \\
T & F & T &  \color{red}{F}  \\
F & F & T &  \color{red}{F} \\
\hline
\end{array}
$$

## filter the assignments {.smaller}

2.  Ask **which of the assignments that remain make the premises true**.

Only two of the rows that remain verify the third premise:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r & \neg (r \to q) & \neg r  \ \\
\hline
T & T & T & F & \color{red}{F} \\
F & T & T & F & \color{red}{F} \\
T & F & T & \color{red}{T} & \color{red}{F}  \\
F & F & T & \color{red}{T} & \color{red}{F} \\
\hline
\end{array}
$$

::: fragment
Check the second premise now:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r & \neg (r \wedge p) & \neg (r \to q) & \neg r  \ \\
\hline
T & F & T & F & \color{red}{T} & \color{red}{F}  \\
F & F & T & \color{red}{T} & \color{red}{T} & \color{red}{F} \\
\hline
\end{array}
$$
:::

## filter the assignments {.smaller}

Check the first premise now:

$$
\begin{array}{|c|c|c|c|c|c|}
\hline
p & q & r & (p \to \neg q) \wedge (q \to \neg r) & \neg (r \wedge p) & \neg (r \to q) & \neg r  \ \\
\hline
F & F & T & F &  \color{red}{T} & \color{red}{T} & \color{red}{F} \\
\hline
\end{array}
$$

We conclude that there is **no counterexample** to validity. **The argument is valid.**
